# Generated by Django 3.1.2 on 2020-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date evenement'),
        ),
    ]
