# Generated by Django 3.1.2 on 2020-11-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20201102_0936'),
        ('events', '0004_auto_20201102_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
    ]
