# Generated by Django 3.1.2 on 2020-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201102_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('soiree', 'soiree'), ('jeux', 'jeux'), ('tourisme', 'tourisme'), ('plein air', 'plein air')], max_length=20, verbose_name='categorie'),
        ),
    ]
