# Generated by Django 3.1.2 on 2020-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='karma',
            name='note',
            field=models.IntegerField(default=0, verbose_name='Note'),
        ),
    ]
