# Generated by Django 3.1.2 on 2021-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_karma_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordonate_x',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='coordonnée X'),
        ),
        migrations.AddField(
            model_name='event',
            name='coordonate_y',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='coordonnée Y'),
        ),
    ]
