# Generated by Django 3.1.2 on 2021-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210218_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordonate_x',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coordonnée X'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordonate_y',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coordonnée Y'),
        ),
    ]
