# Generated by Django 3.1.2 on 2020-11-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('birth_date', models.DateField(verbose_name='date naissance')),
                ('address', models.CharField(max_length=250, verbose_name='adresse')),
                ('zip_code', models.IntegerField(verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('country', models.CharField(max_length=100, verbose_name='pays')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telephone')),
                ('pseudo', models.CharField(max_length=50, verbose_name='pseudo')),
                ('person_type', models.CharField(choices=[('particulier', 'particulier'), ('professionnel', 'professionnel')], max_length=15, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='crée à')),
                ('karma', models.IntegerField(verbose_name='karma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
