# Generated by Django 3.1.2 on 2020-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='karma',
            field=models.IntegerField(blank=True, null=True, verbose_name='karma'),
        ),
    ]
