# Generated by Django 3.1.2 on 2021-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20201104_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imageProfil',
            field=models.FileField(default='events/static/assets/utilisateur-de-profil.svg', null=True, upload_to='', verbose_name='image'),
        ),
    ]
