# Generated by Django 3.1.2 on 2021-02-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_imageprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imageProfil',
            field=models.FileField(default='utilisateur-de-profil.svg', null=True, upload_to='', verbose_name='image'),
        ),
    ]
