# Generated by Django 3.1.2 on 2021-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20210218_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='est visible'),
        ),
    ]
